### ISSUE TITLE
Openlane macro hardening scripts should use 5V SRAM liberty timing files

### ISSUE THREAD

**Issue by antonblanchard** [efabless/caravel_mgmt_soc_gf180mcu#13]
The Openlane scripts are using the 1.8V liberty timing files, and should be using the 5V ones.

**Comment by jeffdi** [comment]
This should be fixed.  Needs review to confirm.

**Comment by jeffdi** [comment]
This was fixed in open-pdks.  Need to be confirmed and closed. @mo-hosni
