### ISSUE TITLE
Add views for sram wrapper

### ISSUE THREAD

**Issue by marwaneltoukhy** [efabless/caravel_mgmt_soc_gf180mcu#16]
all views of sram wrapper should be in the repo

**Comment by mo-hosni** [comment]
#19 
Still missing the mag view of the gf180_ram_512x8_wrapper.

**Comment by jeffdi** [comment]
confirm mag view has been created @marwaneltoukhy

**Comment by marwaneltoukhy** [comment]
Added in https://github.com/efabless/caravel_mgmt_soc_gf180mcu/pull/20
