### ISSUE TITLE
Migrate all updates from caravel_mgmt_soc_litex

### ISSUE THREAD

**Issue by RTimothyEdwards** [efabless/caravel_mgmt_soc_gf180mcu#2]
This is probably/possibly automatic?  Regardless, need confirmation that all updates to caravel_mgmt_soc_litex since the GF test chip taped out are applied to the GF version of the SoC.  This includes, but is not limited to:

(1) User address space (wishbone) recognized as being from 0x3000000 to 0x3fffffff
(2) Housekeeping address space (wishbone) recognized as being from 0x26000000 to 0x26200000

**Comment by jeffdi** [comment]
Silicon test passed .  This should be good.
